name: take_note
description: "Take Note - Modern AI-powered note-taking app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.9
  
  # Supabase Integration
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  
  # Offline Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navigation
  go_router: ^12.1.3
  
  # UI & Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  connectivity_plus: ^5.0.2
  logger: ^2.0.2+1
  device_info_plus: ^10.1.0
  google_fonts: ^6.1.0
  
  # Modern UI & Animations
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  flex_color_scheme: ^7.3.1
  lottie: ^3.1.2
  flutter_svg: ^2.0.9
  
  # HTTP Client
  dio: ^5.4.0
  
  # Code Generation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/onboarding/
